### ISSUE TITLE
Nodes do not de-register themselves with Consul when shutting down.

### ISSUE THREAD

**Issue by jasonluck** [department-of-veterans-affairs/ascent-docker-ami#2]
Nodes are registering with Consul on startup, but do not de-register on shutdown. This leads to a bunch of dead node entires in Consul that all show as failed nodes.

**Comment by stevenwhayes** [comment]
@jasonluck - The documentation states this is built in behavior of Consul, it will reap them after 72 hours (https://www.consul.io/docs/faq.html).  If needed it can be changed in the Consul configuration - https://www.consul.io/docs/agent/options.html#reconnect_timeout.
